#!/bin/bash

echo "***********************************************"
echo "Please type in your password and press enter..."
echo "***********************************************"
echo " "

sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 5044912E
sudo add-apt-repository "deb http://linux.dropbox.com/ubuntu $(lsb_release -sc) main"
sudo apt-get update && sudo apt-get install -f dropbox python-gpgme -y

zenity --info --text 'Successfully Installed' --title 'Complete'
dropbox start -i
exit