#!/bin/bash

echo "***********************************************"
echo "Please type in your password and press enter..."
echo "***********************************************"
echo " "

sudo add-apt-repository ppa:ehoover/compholio -y
sudo apt-get update && sudo apt-get install -f netflix-desktop -y

zenity --info --text 'Successfully Installed' --title 'Complete'
exit