#!/bin/bash

echo "***********************************************"
echo "Please type in your password and press enter..."
echo "***********************************************"
echo " "

sudo apt-get install -f catfish --force-yes -y
zenity --info --text 'Successfully Installed' --title 'Complete'
exit