#!/bin/bash
cd /tmp
wget -O skype-install.deb http://www.skype.com/go/getskype-linux-deb
clear

echo "***********************************************"
echo "Please type in your password and press enter..."
echo "***********************************************"
echo " "

sudo dpkg -i skype-install.deb
sudo apt-get install -f --force-yes -y
rm -rf skype*

zenity --info --text 'Successfully Installed' --title 'Complete'
exit