#!/bin/bash
cd /tmp
wget http://www.teamviewer.com/download/teamviewer_linux.deb
clear

echo "***********************************************"
echo "Please type in your password and press enter..."
echo "***********************************************"
echo " "

sudo dpkg -i teamviewer*
sudo apt-get install -f --force-yes -y
rm -rf teamviewer*

zenity --info --text 'Successfully Installed' --title 'Complete'
exit